In [1]:
import pandas as pd
#from sklearn.neighbors import LocalOutlierFactor 
import pickle
from sklearn.feature_extraction import FeatureHasher

In [2]:
def transform_ip(ip):
    """
    If IPv4, equalizes each group and left zero pads to match IPv6 length
    If IPv6, converts all to lower case
    """
    # IPv4 address
    groups = ip.split( "." )

    equalize_group_length = "".join( map( lambda group: group.zfill(3), groups ))
    return equalize_group_length

In [3]:
ip = '192.31.221.248'
cpf = '34894024407'
qtd_access_ip_last_days=8
qtd_access_cpf_last_days=10

In [4]:
ip = transform_ip(ip)

In [5]:
h = FeatureHasher(n_features=10, input_type='string')
h2 = FeatureHasher(n_features=10, input_type='string')

In [6]:
ip = h.transform([ip]).toarray()[0]
cpf = h2.transform([cpf]).toarray()[0]

In [7]:
ip

array([ 1.,  5., -1., -1.,  0.,  0.,  0., -3.,  0., -1.])

In [8]:
cpf

array([ 1.,  2., -4., -1.,  0.,  0.,  0.,  0.,  1., -2.])

In [9]:
import numpy as np
data = np.concatenate((ip, cpf))
data = list(data)

In [10]:
data.append(qtd_access_ip_last_days)
data.append(qtd_access_cpf_last_days)

In [11]:
print(data)

[1.0, 5.0, -1.0, -1.0, 0.0, 0.0, 0.0, -3.0, 0.0, -1.0, 1.0, 2.0, -4.0, -1.0, 0.0, 0.0, 0.0, 0.0, 1.0, -2.0, 8, 10]


In [12]:
loaded_model = pickle.load(open('login-LocalOutlierFactor.pickle', 'rb'))
loaded_model

LocalOutlierFactor(algorithm='auto', contamination=0.07, leaf_size=30,
                   metric='minkowski', metric_params=None, n_jobs=None,
                   n_neighbors=20, novelty=True, p=2)

In [13]:
loaded_model.predict([data])

array([-1])